FROM arm32v6/node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY server ./server
COPY config ./config

RUN mkdir -p data/logs

EXPOSE 3000 3001

CMD ["node", "server/index.js"]
